  const menu = [
    "Sifat Cahaya",
    "Hukum Pemantulan Sinar",
    "Jumlah Bayangan Pada Cermin Datar",
    "Menghitung sudut sinar pantul",
    "Sifat bayangan pada cermin dengan sudut 180",
    "Sifat bayangan pada cermin cekung",
    "Besaran pada cermin cekung",
    "Pemanfaatan cermin cembung",
    "sifat bayangan yang dibentuk cermin cembung",
    "besaran pada cermin cembung",
    "mengelompokkan alat optik yang menggunakan lensa cembung",
    "besaran pada lensa cembung",
    "bayangan pada lensa divergen",
    "anatomi mata",
    "pembentukan bayangan pada gangguan penglihatan",
    "menghitung kuat lensa",
    "fungsi lapisan atmosfer",
    "lapisan bumi",
    "teori yang dinamika struktur bumi",
    "jenis gerak lempeng",
    "dampak gerak lempeng",
    "tenaga endogen atau eksogen",
    "hiposentrum dan episentrum gempa",
    "tanggap bencana gempa bumi",
    "status gunung api",
    "gelombang gempa berdasarkan seismogram",
    "tanggap bencana erupsi gunung api",
    "potensi bencana tsunami",
    "komponen utama bumi yang mendukung adanya kehidupan",
    "siklus hidrologi",
    "jenis dan besaran pada alat optik",
    "anatomi mata",
    "jenis gangguan mata, solusi, dan menghitung kuat lensa",
    "nama lempeng tektonik di dunia",
    "lapisan atmosfir dan fungsinya",
  ];